name: first workflow

on: push

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Running a sample GitHub Action
        run: echo "This workflow ran successfully"

      - name: Simulating error
        run: echo "error taking place"
